spring:
  application:
    name: Order
  kafka:
    bootstrap-servers: broker1:9092,broker2:9093,broker3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://my-mongo:27017/mydatabase
server:
  servlet:
    context-path: /order
  port: 8080
kafka:
  topic:
    name: order_events